const COMMERCIAL_EMAIL='HC5M7@accor.com';
const FORM_ENDPOINT=`https://formsubmit.co/ajax/${COMMERCIAL_EMAIL}`;

const state={eventType:'',configuration:'',participants:'',eventDate:'',flexibleDate:'non',alternateDate:'',startTime:'',endTime:'',earlyAccess:'non',earlyAccessDuration:'',multipleDays:'non',daysCount:'',confidentiality:'non',activities:[],catering:[],dietary:'',accommodation:'non',rooms:'',arrivalDate:'',departureDate:'',equipment:[],ownEquipment:'non',ownEquipmentDetails:'',comments:'',company:'',name:'',email:'',phone:'',role:''};

const configs={
  cocktail:{label:'Cocktail debout',max:80,validation:false,desc:'Jusqu’à 80 personnes'},
  assis:{label:'Format assis',max:50,validation:false,desc:'Jusqu’à 50 personnes'},
  theatre:{label:'Théâtre',max:50,validation:false,desc:'Jusqu’à 50 personnes'},
  u:{label:'En U',max:50,validation:true,desc:'Jusqu’à 50 personnes, sous réserve de validation'},
  classe:{label:'Classe / École',max:50,validation:true,desc:'Jusqu’à 50 personnes, sous réserve de validation'},
  ilots:{label:'Îlots / Groupes de travail',max:50,validation:true,desc:'Jusqu’à 50 personnes, sous réserve de validation'},
  autre:{label:'Autre configuration',max:50,validation:true,desc:'Jusqu’à 50 personnes, sous réserve de validation'}
};

const eventTypes=['Séminaire','Réunion','Formation','Présentation','Comité de direction','Atelier / Workshop','Cocktail','Déjeuner professionnel','Autre événement professionnel'];
const activityOptions=['Réunion classique','Présentation','Travail en groupe','Workshop','Animation','Team building','Musique','Utilisation d’un micro','Autre','Aucun besoin particulier'];
const cateringOptions=['Café d’accueil','Pause matin','Déjeuner','Pause après-midi','Cocktail','Dîner','Boissons pendant la réunion','Aucun besoin'];
const equipmentOptions=['Écran','Vidéoprojecteur','Connexion HDMI','Wi-Fi','Paperboard','Micro','Sonorisation','Visioconférence','Multiprises','Aucun besoin particulier','Autre'];

let step=0;
let isSubmitting=false;
const app=document.getElementById('app');
const stepLabel=document.getElementById('stepLabel');
const stepCount=document.getElementById('stepCount');
const progressBar=document.getElementById('progressBar');
const steps=[renderIntro,renderEventType,renderConfiguration,renderParticipants,renderDate,renderTimes,renderDuration,renderConfidentiality,renderActivities,renderCatering,renderAccommodation,renderEquipment,renderComments,renderContact,renderSummary];

function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(){updateProgress();steps[step]();window.scrollTo({top:0,behavior:'smooth'});}
function updateProgress(){const n=Math.max(0,step);stepLabel.textContent=step===0?'Bienvenue':`Étape ${n}`;stepCount.textContent=step===0?`${steps.length-1} étapes`:`${n} / ${steps.length-1}`;progressBar.style.width=`${(step/(steps.length-1))*100}%`;}
function next(){if(step<steps.length-1){step++;render();}}
function back(){if(step>0){step--;render();}}
function nav({nextLabel='Continuer',disabled=false,showBack=true}={}){return `<div class="actions">${showBack?'<button class="nav secondary" id="backBtn">Retour</button>':'<span></span>'}<div class="right"><button class="nav primary" id="nextBtn" ${disabled?'disabled':''}>${nextLabel}</button></div></div>`;}
function bindNav(onNext){const b=document.getElementById('backBtn');if(b)b.onclick=back;const n=document.getElementById('nextBtn');if(n)n.onclick=()=>{if(!onNext||onNext()!==false)next();};}
function card(value,label,desc,current){return `<button type="button" class="choice ${current===value?'active':''}" data-value="${esc(value)}"><strong>${esc(label)}</strong>${desc?`<small>${esc(desc)}</small>`:''}</button>`;}
function multiCard(value,current){return `<button type="button" class="choice ${current.includes(value)?'active':''}" data-value="${esc(value)}"><strong>${esc(value)}</strong></button>`;}
function bindSingle(selector,onChange){document.querySelectorAll(selector).forEach(el=>el.onclick=()=>{document.querySelectorAll(selector).forEach(x=>x.classList.remove('active'));el.classList.add('active');onChange(el.dataset.value);const n=document.getElementById('nextBtn');if(n)n.disabled=false;});}
function bindMulti(selector,array,onChange){document.querySelectorAll(selector).forEach(el=>el.onclick=()=>{const v=el.dataset.value;const none=v.includes('Aucun');if(none){array.splice(0,array.length,v);document.querySelectorAll(selector).forEach(x=>x.classList.toggle('active',x===el));}else{const noneIndex=array.findIndex(x=>x.includes('Aucun'));if(noneIndex>=0)array.splice(noneIndex,1);const i=array.indexOf(v);if(i>=0)array.splice(i,1);else array.push(v);el.classList.toggle('active');document.querySelectorAll(selector).forEach(x=>{if(x.dataset.value.includes('Aucun'))x.classList.remove('active');});}if(onChange)onChange();});}
function timeOptions(start='09:00',end='23:00'){const out=[];let [h,m]=start.split(':').map(Number);const [eh,em]=end.split(':').map(Number);while(h<eh||(h===eh&&m<=em)){out.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);m+=30;if(m>=60){h++;m=0;}}return out;}
function fmtDate(d){if(!d)return'—';return new Intl.DateTimeFormat('fr-FR').format(new Date(`${d}T12:00:00`));}
function list(arr){return arr.length?arr.join(', '):'Aucun besoin particulier';}
function calcDuration(){if(!state.startTime||!state.endTime)return'—';const toM=t=>{const [h,m]=t.split(':').map(Number);return h*60+m;};const mins=toM(state.endTime)-toM(state.startTime);return `${Math.floor(mins/60)} h${mins%60?` ${mins%60} min`:''}`;}
function earlyAccessStatus(){if(state.earlyAccess!=='oui'||!state.startTime||!state.earlyAccessDuration)return'Compatible';const mins={'15 minutes':15,'30 minutes':30,'45 minutes':45,'1 heure':60,'Plus d’une heure':90}[state.earlyAccessDuration]||0;const [h,m]=state.startTime.split(':').map(Number);return h*60+m-mins<540?'⚠️ Accès souhaité avant 09h00 — à ajuster':'Compatible';}
function validationStatus(){const w=[];if(configs[state.configuration]?.validation)w.push('configuration');if(state.confidentiality!=='non')w.push('confidentialité');if(state.activities.some(v=>['Animation','Team building','Musique','Utilisation d’un micro'].includes(v)))w.push('activité / niveau sonore');if(earlyAccessStatus().startsWith('⚠️'))w.push('accès anticipé');return w;}
function summaryRow(label,value){return `<div class="summary-row"><span>${label}</span><strong>${value||'—'}</strong></div>`;}

function renderIntro(){app.innerHTML=`<div class="question"><div class="tag">Votre événement</div><h2>Parlez-nous de votre projet.</h2><p class="helper">En quelques étapes, nous allons recueillir les informations nécessaires pour permettre à notre service commercial d’étudier votre demande et de vous adresser une proposition adaptée.</p><div class="notice">Notre espace événementiel est intégré à l’activité de l’hôtel. Le formulaire adapte automatiquement les capacités selon la configuration souhaitée.</div>${nav({nextLabel:'Décrire mon projet',showBack:false})}</div>`;bindNav();}

function renderEventType(){app.innerHTML=`<div class="question"><div class="tag">Événement</div><h2>Quel type d’événement souhaitez-vous organiser ?</h2><p class="helper">Choisissez la catégorie qui correspond le mieux à votre projet.</p><div class="grid">${eventTypes.map(v=>card(v,v,'',state.eventType)).join('')}</div>${nav({disabled:!state.eventType})}</div>`;bindSingle('.choice',v=>state.eventType=v);bindNav();}

function renderConfiguration(){app.innerHTML=`<div class="question"><div class="tag">Configuration</div><h2>Quelle configuration souhaitez-vous ?</h2><p class="helper">La capacité maximale dépend de la disposition choisie.</p><div class="grid">${Object.entries(configs).map(([k,c])=>card(k,c.label,c.desc,state.configuration)).join('')}</div>${state.configuration&&configs[state.configuration].validation?'<div class="notice warn">Cette configuration reste sous réserve de validation par notre service commercial.</div>':''}${nav({disabled:!state.configuration})}</div>`;bindSingle('.choice',v=>{state.configuration=v;const max=configs[v].max;if(Number(state.participants)>max)state.participants='';renderConfiguration();});bindNav();}

function renderParticipants(){const cfg=configs[state.configuration];const options=Array.from({length:cfg.max},(_,i)=>i+1);app.innerHTML=`<div class="question"><div class="tag">Participants</div><h2>Combien de personnes prévoyez-vous ?</h2><p class="helper">Configuration sélectionnée : <strong>${esc(cfg.label)}</strong>.</p><div class="field"><label for="participants">Nombre de participants</label><select id="participants"><option value="">Sélectionner</option>${options.map(n=>`<option value="${n}" ${String(n)===String(state.participants)?'selected':''}>${n} personne${n>1?'s':''}</option>`).join('')}</select></div>${cfg.validation?'<div class="notice warn">La faisabilité exacte de cette disposition sera confirmée par le service commercial.</div>':''}${nav({disabled:!state.participants})}</div>`;const s=document.getElementById('participants');s.onchange=()=>{state.participants=s.value;document.getElementById('nextBtn').disabled=!s.value;};bindNav();}

function renderDate(){const min=new Date().toISOString().split('T')[0];app.innerHTML=`<div class="question"><div class="tag">Date</div><h2>Quand souhaitez-vous organiser votre événement ?</h2><div class="field"><label>Date souhaitée</label><input id="eventDate" type="date" min="${min}" value="${esc(state.eventDate)}"></div><p class="helper">Votre date est-elle flexible ?</p><div class="grid"><button class="choice ${state.flexibleDate==='non'?'active':''}" data-flex="non"><strong>Non</strong></button><button class="choice ${state.flexibleDate==='oui'?'active':''}" data-flex="oui"><strong>Oui</strong></button></div><div id="altWrap" class="field" style="margin-top:16px;${state.flexibleDate==='oui'?'':'display:none'}"><label>Autre date possible</label><input id="alternateDate" type="date" min="${min}" value="${esc(state.alternateDate)}"></div>${nav({disabled:!state.eventDate})}</div>`;const d=document.getElementById('eventDate');d.onchange=()=>{state.eventDate=d.value;document.getElementById('nextBtn').disabled=!d.value;};document.querySelectorAll('[data-flex]').forEach(el=>el.onclick=()=>{state.flexibleDate=el.dataset.flex;renderDate();});const a=document.getElementById('alternateDate');if(a)a.onchange=()=>state.alternateDate=a.value;bindNav();}

function renderTimes(){const starts=timeOptions('09:00','22:30');const ends=state.startTime?timeOptions(add30(state.startTime),'23:00'):[];app.innerHTML=`<div class="question"><div class="tag">Horaires</div><h2>Quels horaires souhaitez-vous ?</h2><p class="helper">Notre espace est disponible à partir de 09h00 et jusqu’à 23h00.</p><div class="grid"><div class="field"><label>Heure de début</label><select id="startTime"><option value="">Sélectionner</option>${starts.map(t=>`<option ${state.startTime===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Heure de fin</label><select id="endTime" ${!state.startTime?'disabled':''}><option value="">Sélectionner</option>${ends.map(t=>`<option ${state.endTime===t?'selected':''}>${t}</option>`).join('')}</select></div></div><p class="helper">Avez-vous besoin d’accéder à la salle avant le début de l’événement pour votre installation ?</p><div class="grid"><button class="choice ${state.earlyAccess==='non'?'active':''}" data-access="non"><strong>Non</strong></button><button class="choice ${state.earlyAccess==='oui'?'active':''}" data-access="oui"><strong>Oui</strong></button></div>${state.earlyAccess==='oui'?`<div class="field" style="margin-top:16px"><label>Temps d’installation souhaité</label><select id="earlyDuration"><option value="">Sélectionner</option>${['15 minutes','30 minutes','45 minutes','1 heure','Plus d’une heure'].map(v=>`<option ${state.earlyAccessDuration===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="notice warn">L’accès physique à l’espace ne peut pas avoir lieu avant 09h00.</div>`:''}${nav({disabled:!state.startTime||!state.endTime||(state.earlyAccess==='oui'&&!state.earlyAccessDuration)})}</div>`;const s=document.getElementById('startTime');s.onchange=()=>{state.startTime=s.value;state.endTime='';renderTimes();};const e=document.getElementById('endTime');if(e)e.onchange=()=>{state.endTime=e.value;document.getElementById('nextBtn').disabled=!state.endTime||(state.earlyAccess==='oui'&&!state.earlyAccessDuration);};document.querySelectorAll('[data-access]').forEach(el=>el.onclick=()=>{state.earlyAccess=el.dataset.access;if(state.earlyAccess==='non')state.earlyAccessDuration='';renderTimes();});const ed=document.getElementById('earlyDuration');if(ed)ed.onchange=()=>{state.earlyAccessDuration=ed.value;document.getElementById('nextBtn').disabled=!ed.value||!state.startTime||!state.endTime;};bindNav();}
function add30(t){let [h,m]=t.split(':').map(Number);m+=30;if(m>=60){h++;m=0;}return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;}

function renderDuration(){app.innerHTML=`<div class="question"><div class="tag">Durée</div><h2>Votre événement se déroule-t-il sur plusieurs jours ?</h2><div class="grid"><button class="choice ${state.multipleDays==='non'?'active':''}" data-days="non"><strong>Non</strong></button><button class="choice ${state.multipleDays==='oui'?'active':''}" data-days="oui"><strong>Oui</strong></button></div>${state.multipleDays==='oui'?`<div class="field" style="margin-top:16px"><label>Nombre de jours</label><select id="daysCount"><option value="">Sélectionner</option>${Array.from({length:10},(_,i)=>i+2).map(n=>`<option value="${n}" ${String(state.daysCount)===String(n)?'selected':''}>${n} jours</option>`).join('')}</select></div>`:''}${nav({disabled:state.multipleDays==='oui'&&!state.daysCount})}</div>`;document.querySelectorAll('[data-days]').forEach(el=>el.onclick=()=>{state.multipleDays=el.dataset.days;if(state.multipleDays==='non')state.daysCount='';renderDuration();});const d=document.getElementById('daysCount');if(d)d.onchange=()=>{state.daysCount=d.value;document.getElementById('nextBtn').disabled=!d.value;};bindNav();}

function renderConfidentiality(){const opts=[['non','Pas de besoin particulier'],['oui','Oui'],['importante','Confidentialité importante']];app.innerHTML=`<div class="question"><div class="tag">Confidentialité</div><h2>Votre événement nécessite-t-il un niveau de confidentialité particulier ?</h2><p class="helper">Notre espace est intégré à l’activité de l’hôtel ; cette information nous aide à vérifier la compatibilité de votre demande.</p><div class="grid">${opts.map(([v,l])=>card(v,l,'',state.confidentiality)).join('')}</div>${state.confidentiality!=='non'?'<div class="notice warn">Ce point sera vérifié par notre service commercial.</div>':''}${nav()}</div>`;bindSingle('.choice',v=>{state.confidentiality=v;renderConfidentiality();});bindNav();}

function renderActivities(){app.innerHTML=`<div class="question"><div class="tag">Déroulement</div><h2>Prévoyez-vous des activités particulières ?</h2><p class="helper">Plusieurs réponses sont possibles.</p><div class="grid">${activityOptions.map(v=>multiCard(v,state.activities)).join('')}</div>${nav()}</div>`;bindMulti('.choice',state.activities);bindNav();}

function renderCatering(){app.innerHTML=`<div class="question"><div class="tag">Restauration</div><h2>Souhaitez-vous prévoir des prestations de restauration ?</h2><p class="helper">Plusieurs réponses sont possibles.</p><div class="grid">${cateringOptions.map(v=>multiCard(v,state.catering)).join('')}</div><div class="field" style="margin-top:20px"><label>Allergies ou régimes alimentaires à signaler</label><textarea id="dietary" placeholder="Facultatif">${esc(state.dietary)}</textarea></div>${nav()}</div>`;bindMulti('.choice',state.catering);document.getElementById('dietary').oninput=e=>state.dietary=e.target.value;bindNav();}

function renderAccommodation(){app.innerHTML=`<div class="question"><div class="tag">Hébergement</div><h2>Avez-vous également besoin de chambres ?</h2><div class="grid"><button class="choice ${state.accommodation==='non'?'active':''}" data-room="non"><strong>Non</strong></button><button class="choice ${state.accommodation==='oui'?'active':''}" data-room="oui"><strong>Oui</strong></button></div>${state.accommodation==='oui'?`<div class="grid" style="margin-top:18px"><div class="field"><label>Nombre de chambres</label><select id="rooms"><option value="">Sélectionner</option>${Array.from({length:80},(_,i)=>i+1).map(n=>`<option value="${n}" ${String(state.rooms)===String(n)?'selected':''}>${n}</option>`).join('')}</select></div><div></div><div class="field"><label>Date d’arrivée</label><input id="arrival" type="date" value="${esc(state.arrivalDate)}"></div><div class="field"><label>Date de départ</label><input id="departure" type="date" value="${esc(state.departureDate)}"></div></div>`:''}${nav({disabled:state.accommodation==='oui'&&(!state.rooms||!state.arrivalDate||!state.departureDate)})}</div>`;document.querySelectorAll('[data-room]').forEach(el=>el.onclick=()=>{state.accommodation=el.dataset.room;if(state.accommodation==='non'){state.rooms='';state.arrivalDate='';state.departureDate='';}renderAccommodation();});['rooms','arrival','departure'].forEach(id=>{const el=document.getElementById(id);if(el)el.onchange=()=>{if(id==='rooms')state.rooms=el.value;if(id==='arrival')state.arrivalDate=el.value;if(id==='departure')state.departureDate=el.value;document.getElementById('nextBtn').disabled=!state.rooms||!state.arrivalDate||!state.departureDate;};});bindNav();}

function renderEquipment(){app.innerHTML=`<div class="question"><div class="tag">Matériel</div><h2>De quel matériel aurez-vous besoin ?</h2><p class="helper">Plusieurs réponses sont possibles.</p><div class="grid">${equipmentOptions.map(v=>multiCard(v,state.equipment)).join('')}</div><p class="helper" style="margin-top:22px">Prévoyez-vous d’apporter votre propre matériel ?</p><div class="grid"><button class="choice ${state.ownEquipment==='non'?'active':''}" data-own="non"><strong>Non</strong></button><button class="choice ${state.ownEquipment==='oui'?'active':''}" data-own="oui"><strong>Oui</strong></button></div>${state.ownEquipment==='oui'?`<div class="field" style="margin-top:16px"><label>Précisez le matériel apporté</label><textarea id="ownDetails">${esc(state.ownEquipmentDetails)}</textarea></div>`:''}${nav()}</div>`;bindMulti('.choice:not([data-own])',state.equipment);document.querySelectorAll('[data-own]').forEach(el=>el.onclick=()=>{state.ownEquipment=el.dataset.own;if(state.ownEquipment==='non')state.ownEquipmentDetails='';renderEquipment();});const o=document.getElementById('ownDetails');if(o)o.oninput=e=>state.ownEquipmentDetails=e.target.value;bindNav();}

function renderComments(){app.innerHTML=`<div class="question"><div class="tag">Précisions</div><h2>Souhaitez-vous ajouter une information sur votre projet ?</h2><p class="helper">Déroulement prévu, attentes particulières, organisation de la journée…</p><div class="field"><textarea id="comments" placeholder="Facultatif">${esc(state.comments)}</textarea></div>${nav()}</div>`;document.getElementById('comments').oninput=e=>state.comments=e.target.value;bindNav();}

function renderContact(){app.innerHTML=`<div class="question"><div class="tag">Coordonnées</div><h2>Comment notre équipe peut-elle vous recontacter ?</h2><div class="grid"><div class="field"><label>Société *</label><input id="company" value="${esc(state.company)}"></div><div class="field"><label>Nom et prénom *</label><input id="name" value="${esc(state.name)}"></div><div class="field"><label>Adresse e-mail *</label><input id="email" type="email" value="${esc(state.email)}"></div><div class="field"><label>Téléphone *</label><input id="phone" type="tel" value="${esc(state.phone)}"></div><div class="field"><label>Fonction</label><input id="role" value="${esc(state.role)}"></div></div>${nav({disabled:!contactValid()})}</div>`;['company','name','email','phone','role'].forEach(id=>document.getElementById(id).oninput=e=>{state[id]=e.target.value;document.getElementById('nextBtn').disabled=!contactValid();});bindNav();}
function contactValid(){return state.company.trim()&&state.name.trim()&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email.trim())&&state.phone.trim();}

function renderSummary(){const cfg=configs[state.configuration],warnings=validationStatus();app.innerHTML=`<div class="question"><div class="tag">Récapitulatif</div><h2>Vérifiez votre demande avant envoi.</h2><p class="helper">Le récapitulatif sera transmis automatiquement au service commercial.</p><div class="summary"><div class="summary-section"><h3>Client</h3>${summaryRow('Société',esc(state.company))}${summaryRow('Contact',esc(state.name))}${summaryRow('E-mail',esc(state.email))}${summaryRow('Téléphone',esc(state.phone))}${summaryRow('Fonction',esc(state.role)||'—')}</div><div class="summary-section"><h3>Événement</h3>${summaryRow('Type',esc(state.eventType))}${summaryRow('Date',fmtDate(state.eventDate))}${state.flexibleDate==='oui'?summaryRow('Autre date possible',fmtDate(state.alternateDate)):''}${summaryRow('Horaires',`${state.startTime} – ${state.endTime}`)}${summaryRow('Durée',calcDuration())}${summaryRow('Configuration',esc(cfg.label))}${summaryRow('Participants',`${state.participants} / ${cfg.max} max.`)}${summaryRow('Plusieurs jours',state.multipleDays==='oui'?`${state.daysCount} jours`:'Non')}${summaryRow('Accès anticipé',state.earlyAccess==='oui'?`${esc(state.earlyAccessDuration)} — ${earlyAccessStatus()}`:'Non')}</div><div class="summary-section"><h3>Prestations</h3>${summaryRow('Restauration',esc(list(state.catering)))}${summaryRow('Hébergement',state.accommodation==='oui'?`${state.rooms} chambres, du ${fmtDate(state.arrivalDate)} au ${fmtDate(state.departureDate)}`:'Non')}${summaryRow('Matériel',esc(list(state.equipment)))}</div><div class="summary-section"><h3>Analyse</h3>${summaryRow('Confidentialité',state.confidentiality==='non'?'Pas de besoin particulier':esc(state.confidentiality))}${summaryRow('Activités',esc(list(state.activities)))}${summaryRow('Statut',warnings.length?`<span class="status warn">⚠️ À valider : ${warnings.join(', ')}</span>`:'<span class="status">✓ Aucun point bloquant identifié</span>')}</div>${state.comments||state.dietary?`<div class="summary-section"><h3>Informations complémentaires</h3>${state.comments?summaryRow('Commentaires',esc(state.comments)):''}${state.dietary?summaryRow('Régimes / allergies',esc(state.dietary)):''}</div>`:''}</div><div class="notice" style="margin-top:18px"><label class="checkline"><input type="checkbox" id="consent"><span>J’accepte que les informations renseignées soient transmises à l’hôtel afin que le service commercial puisse étudier ma demande et me recontacter.</span></label></div>${nav({nextLabel:'Envoyer ma demande',disabled:true})}</div>`;const c=document.getElementById('consent'),n=document.getElementById('nextBtn');c.onchange=()=>n.disabled=!c.checked;const b=document.getElementById('backBtn');if(b)b.onclick=back;n.onclick=()=>{if(c.checked)submitRequest();};}

function payload(){const cfg=configs[state.configuration],warnings=validationStatus();return {_subject:`Nouvelle demande séminaire – ${state.company} – ${fmtDate(state.eventDate)} – ${state.participants} pers.`,_template:'table',_replyto:state.email,'Société':state.company,'Contact':state.name,'Fonction':state.role||'—','E-mail client':state.email,'Téléphone':state.phone,'Type d’événement':state.eventType,'Date souhaitée':fmtDate(state.eventDate),'Date flexible':state.flexibleDate==='oui'?'Oui':'Non','Autre date possible':state.flexibleDate==='oui'?fmtDate(state.alternateDate):'—','Horaires':`${state.startTime} – ${state.endTime}`,'Durée':calcDuration(),'Configuration':cfg.label,'Participants':`${state.participants} / ${cfg.max} max.`,'Événement sur plusieurs jours':state.multipleDays==='oui'?`${state.daysCount} jours`:'Non','Accès anticipé':state.earlyAccess==='oui'?`${state.earlyAccessDuration} — ${earlyAccessStatus()}`:'Non','Confidentialité':state.confidentiality==='non'?'Pas de besoin particulier':state.confidentiality,'Activités':list(state.activities),'Restauration':list(state.catering),'Régimes / allergies':state.dietary||'—','Hébergement':state.accommodation==='oui'?`${state.rooms} chambres, du ${fmtDate(state.arrivalDate)} au ${fmtDate(state.departureDate)}`:'Non','Matériel demandé':list(state.equipment),'Matériel apporté par le client':state.ownEquipment==='oui'?(state.ownEquipmentDetails||'Oui, non précisé'):'Non','Commentaires':state.comments||'—','Analyse automatique':warnings.length?`À valider : ${warnings.join(', ')}`:'Aucun point bloquant identifié','Origine':'Formulaire séminaire du site internet'};}

async function submitRequest(){if(isSubmitting)return;isSubmitting=true;localStorage.setItem('seminaire_request',JSON.stringify(state));const btn=document.getElementById('nextBtn');if(btn){btn.disabled=true;btn.textContent='Envoi en cours…';}try{const r=await fetch(FORM_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload())});const data=await r.json().catch(()=>({}));if(!r.ok||data.success===false)throw new Error(data.message||'Erreur d’envoi');localStorage.removeItem('seminaire_request');progressBar.style.width='100%';stepLabel.textContent='Demande envoyée';stepCount.textContent='';app.innerHTML=`<div class="success"><div class="icon">✓</div><h2>Votre demande a bien été envoyée.</h2><p>Merci ${esc(state.name)}. Votre récapitulatif a été transmis à notre service commercial. Notre équipe va étudier votre projet et reviendra vers vous avec une proposition adaptée.</p><div class="actions" style="justify-content:center;margin-top:24px"><button class="nav secondary" id="restart">Faire une nouvelle demande</button><button class="nav primary" id="download">Télécharger mon récapitulatif</button></div></div>`;document.getElementById('restart').onclick=()=>location.reload();document.getElementById('download').onclick=downloadSummary;}catch(e){isSubmitting=false;app.innerHTML=`<div class="success"><div class="icon">!</div><h2>L’envoi n’a pas abouti.</h2><p>La demande n’a pas été confirmée comme transmise. Vous pouvez réessayer ou télécharger le récapitulatif.</p><div class="notice warn" style="margin-top:18px">Lors du tout premier test, l’adresse de réception peut devoir être activée depuis l’e-mail de confirmation envoyé par le service de formulaire.</div><div class="actions" style="justify-content:center;margin-top:24px"><button class="nav secondary" id="download">Télécharger le récapitulatif</button><button class="nav primary" id="retry">Réessayer l’envoi</button></div></div>`;document.getElementById('download').onclick=downloadSummary;document.getElementById('retry').onclick=submitRequest;}}

function downloadSummary(){const cfg=configs[state.configuration],warnings=validationStatus();const text=`DEMANDE SÉMINAIRE\n\nCLIENT\nSociété : ${state.company}\nContact : ${state.name}\nE-mail : ${state.email}\nTéléphone : ${state.phone}\n\nÉVÉNEMENT\nType : ${state.eventType}\nDate : ${fmtDate(state.eventDate)}\nHoraires : ${state.startTime} - ${state.endTime}\nDurée : ${calcDuration()}\nConfiguration : ${cfg.label}\nParticipants : ${state.participants} / ${cfg.max} max.\n\nRESTAURATION\n${list(state.catering)}\n\nHÉBERGEMENT\n${state.accommodation==='oui'?`${state.rooms} chambres - du ${fmtDate(state.arrivalDate)} au ${fmtDate(state.departureDate)}`:'Non'}\n\nMATÉRIEL\n${list(state.equipment)}\n\nCOMMENTAIRES\n${state.comments||'—'}\n\nANALYSE AUTOMATIQUE\n${warnings.length?'À valider : '+warnings.join(', '):'Aucun point bloquant identifié'}\n`;const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`demande-seminaire-${state.company.toLowerCase().replace(/[^a-z0-9]+/gi,'-')||'client'}.txt`;a.click();URL.revokeObjectURL(a.href);}

render();
